In [1]:
import pandas as pd
import numpy as np
import os
from nltk.tokenize import word_tokenize

In [2]:
from IPython.display import HTML
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
#Setting working directory
#Desktop
os.chdir("C:/Users/john/Documents/GitHub_Data/VCAP-Open-Hours-Project-Data")
#Laptop
#os.chdir('C:/Users/johnc/Documents/GitHub_Data/VCAP-Open-Hours-Project-Data')

### READ ME

In [8]:
## Update, I am grabbing census tracts and counties and states for other clinics

In [11]:
other_addresses = pd.read_csv("other_geo_coded_addresses.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8902 entries, 0 to 8901
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      8902 non-null   int64
 1   full_address    8902 non-null   object
 2   lat             8902 non-null   float64
 3   long            8902 non-null   float64
 4   google_address  8902 non-null   object
 5   place_id        8902 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 417.4+ KB

The purpose of this script is to add the census tract to the vet clinic address. Sometimes the api times out, so I need to be able to continually append to the same list

In [17]:
census_tract_join_dict = {"full_address" : [],
                           "full_census_tract" : []}

In [37]:
new_table = other_addresses.loc[8368:]
new_table.head()

,Unnamed: 0,full_address,lat,long,google_address,place_id
8368,8368,"SMALL ANIMAL HOSPITAL INC, 2340 N NEWHALL ST, ...",43.061010,-87.890108,"2340 N Newhall St, Milwaukee, WI 53211, USA",ChIJabs9ht4YBYgRqwHDgg-U5WE
8369,8369,"CENTRE EQUINE PRACTICE, 164 TUSSEY SINK RD, CE...",40.786034,-77.698906,"164 Tussey Sink Rd, Centre Hall, PA 16828, USA",ChIJb39Wv326zokR0-WtNQz0-BU
8370,8370,"LOYALSOCK ANIMAL HOSPITAL INC, 1900 NORTHWAY R...",41.261638,-76.969927,"1900 Northway Rd, Williamsport, PA 17701, USA",ChIJuYqa_9Olz4kRd71_7-iuepE
8371,8371,"CORY WILLIAMS DVM PLLC, 5866 ATHENS WALNUT HIL...",37.944133,-84.379072,"5866 Athens Walnut Hill Rd, Lexington, KY 4051...",ChIJyZ_vODlRQogRnTibUI1QkHA
8372,8372,"SONO VET VISION LLC, 2413 KAYLONNI LN, VAN BUR...",35.463203,-94.399951,"2413 Kaylonni Ln, Van Buren, AR 72956, USA",ChIJC5q4iMpKyocRDKVlKReoUzg

In [14]:
new_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8902 entries, 0 to 8901
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      8902 non-null   int64
 1   full_address    8902 non-null   object
 2   lat             8902 non-null   float64
 3   long            8902 non-null   float64
 4   google_address  8902 non-null   object
 5   place_id        8902 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 417.4+ KB

In [38]:
import censusgeocode as cg 

for ad, lat, lng in zip(new_table["full_address"], new_table["lat"], new_table["long"]):
    try:
        result = cg.coordinates(x=lng, y=lat)
        full_census_tract = result["Census Tracts"][0]["NAME"] + ", " + result['Counties'][0]['NAME'] + ", " + result["States"][0]['NAME']
        census_tract_join_dict["full_address"].append(ad)
        census_tract_join_dict["full_census_tract"].append(full_census_tract)
    except ValueError:
        census_tract_join_dict["full_address"].append(ad)
        census_tract_join_dict["full_census_tract"].append("Not Found")

In [40]:
other_address_tracts = pd.DataFrame(census_tract_join_dict)
other_address_tracts.tail()
len(other_address_tracts)

,full_address,full_census_tract
8897,"TIMBERLYNE ANIMAL CLINIC INC, 1703 LEGION RD #...","Census Tract 121.01, Orange County, North Caro..."
8898,"SOUTH TX VET SPECLSTS LLP, 503 E SONTERRA BLVD...","Census Tract 1918.18, Bexar County, Texas"
8899,"KEVIN A MONCE DVM, 305 ASHVILLE AVE, CARY, NC,...","Census Tract 535.09, Wake County, North Carolina"
8900,"PLANTATION ANIMAL HOSP-MTTHWS, 3036 WEDDINGTON...","Census Tract 58.51, Mecklenburg County, North ..."
8901,"ALT VET IMAGING, 7629 UNIVERSITY DR, SHREVEPOR...","Census Tract 239.04, Caddo Parish, Louisiana"

8902

In [41]:
other_addresses = other_addresses.merge(other_address_tracts, on='full_address', how='left')

In [45]:
other_addresses.to_csv("other_geo_coded_addresses.csv")

In [4]:
#Reading in Data

In [5]:
#All addresses list
all_addresses = pd.read_csv("all_geocoded_addresses.csv")
#census tract join table
#census_tract_join_table = pd.read_csv("census_tract_join_table.csv")

In [6]:
all_addresses_join_table = all_addresses[["full_address", "lat", "long"]]

In [7]:
len(all_addresses_join_table)

23637

In [32]:
#census_tract_join_dict = {"full_address" : [],
#                           "full_census_tract" : []}

In [47]:
len(census_tract_join_dict['full_address'])

16115

In [54]:
new_table = all_addresses_join_table.loc[16115:]

In [55]:
new_table.head()

                                            full_address        lat       long
16115  ALVIN-FRIENDSWOOD VET CLINIC, 2407 W PARKWOOD ...  29.482395 -95.217793
16116  EASTON COMMONS ANIMAL HOSPITAL, 15030 WEST RD,...  29.900835 -95.628488
16117  VCA SOUTHWEST FREEWAY ANIMAL, 15575 SOUTHWEST ...  29.602112 -95.617226
16118  VALLEY ANIMAL HOSPITAL LLC, 520 E RIDGE RD, PA...  40.320400 -76.595854
16119  PETVET, 6763 HIGHWAY 6 S # 1800, HOUSTON, TX, ...  29.704405 -95.642775

In [56]:
import censusgeocode as cg 

for ad, lat, lng in zip(new_table["full_address"], new_table["lat"], new_table["long"]):
    try:
        result = cg.coordinates(x=lng, y=lat)
        full_census_tract = result["Census Tracts"][0]["NAME"] + ", " + result['Counties'][0]['NAME'] + ", " + result["States"][0]['NAME']
        census_tract_join_dict["full_address"].append(ad)
        census_tract_join_dict["full_census_tract"].append(full_census_tract)
    except ValueError:
        census_tract_join_dict["full_address"].append(ad)
        census_tract_join_dict["full_census_tract"].append("Not Found")

,full_address,full_census_tract
23632,"HEALING HANDS VETERINARY HOSP, 7427 N LOOP 160...","Census Tract 1820.03, Bexar County, Texas"
23633,"BROOKWOOD ANIMAL HOSP-JENNIFER, 922 DOGWOOD RD...","Census Tract 507.56, Gwinnett County, Georgia"
23634,"SHORE KAREN BVMS, 5280 PACHECO BLVD, PACHECO, ...","Census Tract 3212, Contra Costa County, Califo..."
23635,"BORGFELD ANIMAL HOSPITAL PLLC, 1304 W BORGFELD...","Census Tract 1918.04, Bexar County, Texas"
23636,"ATLANTIC ANIMAL HOSPITAL PA, 1319 MILITARY CUT...","Census Tract 106, New Hanover County, North Ca..."

In [62]:
census_tract_join_table = pd.DataFrame(census_tract_join_dict)

In [63]:
census_tract_join_table.to_csv("census_tract_join_table.csv")

In [68]:
import censusgeocode as cg 

cg.coordinates(x = -73.25840, y = 41.31197)

{'States': [{'STATENS': '01779780',
   'GEOID': '09',
   'CENTLAT': '+41.5751437',
   'AREAWATER': 1816364426,
   'STATE': '09',
   'BASENAME': 'Connecticut',
   'STUSAB': 'CT',
   'OID': '27490331955805',
   'LSADC': '00',
   'FUNCSTAT': 'A',
   'INTPTLAT': '+41.5798637',
   'DIVISION': '1',
   'NAME': 'Connecticut',
   'REGION': '1',
   'OBJECTID': 26,
   'CENTLON': '-072.7393081',
   'AREALAND': 12541750274,
   'INTPTLON': '-072.7466572',
   'MTFCC': 'G4000',
   'CENT': (-72.7393081, 41.5751437),
   'INTPT': (-72.7466572, 41.5798637)}],
 'County Subdivisions': [{'COUSUB': '48620',
   'GEOID': '0912048620',
   'CENTLAT': '+41.3379086',
   'AREAWATER': 511097,
   'STATE': '09',
   'BASENAME': 'Monroe',
   'OID': '27690697821317',
   'LSADC': '43',
   'FUNCSTAT': 'A',
   'INTPTLAT': '+41.3392358',
   'NAME': 'Monroe town',
   'OBJECTID': 23356,
   'CENTLON': '-073.2250242',
   'COUSUBCC': 'T1',
   'AREALAND': 67522444,
   'INTPTLON': '-073.2228275',
   'MTFCC': 'G4040',
   'COUSUBNS': '00213463',
   'COUNTY': '120',
   'CENT': (-73.2250242, 41.3379086),
   'INTPT': (-73.2228275, 41.3392358)}],
 'Census Designated Places': [{'NECTAPCI': 'N',
   'GEOID': '0973280',
   'CENTLAT': '+41.3255913',
   'AREAWATER': 26341,
   'STATE': '09',
   'BASENAME': 'Stepney',
   'OID': '2809015672789246',
   'LSADC': '57',
   'PLACE': '73280',
   'FUNCSTAT': 'S',
   'INTPTLAT': '+41.3243559',
   'NAME': 'Stepney CDP',
   'OBJECTID': 29334,
   'PLACECC': 'U1',
   'CENTLON': '-073.2673941',
   'CBSAPCI': 'N',
   'AREALAND': 17400029,
   'INTPTLON': '-073.2683914',
   'PLACENS': '02805970',
   'MTFCC': 'G4210',
   'CENT': (-73.2673941, 41.3255913),
   'INTPT': (-73.2683914, 41.3243559)}],
 'Counties': [{'GEOID': '09120',
   'CENTLAT': '+41.1850360',
   'AREAWATER': 253764138,
   'STATE': '09',
   'BASENAME': 'Greater Bridgeport',
   'OID': '2759030115366155',
   'LSADC': 'PL',
   'FUNCSTAT': 'N',
   'INTPTLAT': '+41.1845583',
   'NAME': 'Greater Bridgeport Planning Region',
   'OBJECTID': 1408,
   'CENTLON': '-073.2084531',
   'COUNTYCC': 'H5',
   'COUNTYNS': '02830245',
   'AREALAND': 363067866,
   'INTPTLON': '-073.2094009',
   'MTFCC': 'G4020',
   'COUNTY': '120',
   'CENT': (-73.2084531, 41.185036),
   'INTPT': (-73.2094009, 41.1845583)}],
 '2022 State Legislative Districts - Upper': [{'GEOID': '09022',
   'CENTLAT': '+41.2596247',
   'AREAWATER': 1876068,
   'STATE': '09',
   'BASENAME': '22',
   'OID': '2129031808685162',
   'SLDU': '022',
   'LSADC': 'LU',
   'FUNCSTAT': 'N',
   'INTPTLAT': '+41.2582157',
   'NAME': 'State Senate District 22',
   'OBJECTID': 1694,
   'CENTLON': '-073.2149370',
   'LSY': '2022',
   'AREALAND': 96693365,
   'INTPTLON': '-073.2143698',
   'MTFCC': 'G5210',
   'LDTYP': 'O',
   'CENT': (-73.214937, 41.2596247),
   'INTPT': (-73.2143698, 41.2582157)}],
 '2022 State Legislative Districts - Lower': [{'GEOID': '09112',
   'CENTLAT': '+41.3175344',
   'SLDL': '112',
   'AREAWATER': 2646116,
   'STATE': '09',
   'BASENAME': '112',
   'OID': '2139031808685190',
   'LSADC': 'LL',
   'FUNCSTAT': 'N',
   'INTPTLAT': '+41.3118483',
   'NAME': 'State House District 112',
   'OBJECTID': 2057,
   'CENTLON': '-073.2368743',
   'LSY': '2022',
   'AREALAND': 91789415,
   'INTPTLON': '-073.2401357',
   'MTFCC': 'G5220',
   'LDTYP': 'O',
   'CENT': (-73.2368743, 41.3175344),
   'INTPT': (-73.2401357, 41.3118483)}],
 '2020 Census Blocks': [{'SUFFIX': '',
   'GEOID': '090011001003004',
   'CENTLAT': '+41.3152785',
   'OID_1': '',
   'BLOCK': '3004',
   'AREAWATER': 0,
   'STATE': '09',
   'BASENAME': '3004',
   'LSADC': 'BK',
   'INTPTLAT': '+41.3152785',
   'FUNCSTAT': 'S',
   'NAME': 'Block 3004',
   'OBJECTID': 585241,
   'TRACT': '100100',
   'CENTLON': '-073.2568549',
   'AREA': 1515742.82316088,
   'LEN': 6602.40658152326,
   'BLKGRP': '3',
   'AREALAND': 854336,
   'INTPTLON': '-073.2568549',
   'MTFCC': 'G5040',
   'LWBLKTYP': 'L',
   'UR': 'R',
   'COUNTY': '001',
   'CENT': (-73.2568549, 41.3152785),
   'INTPT': (-73.2568549, 41.3152785)}],
 'Census Tracts': [{'GEOID': '09120100100',
   'CENTLAT': '+41.3221984',
   'AREAWATER': 26341,
   'STATE': '09',
   'BASENAME': '1001',
   'OID': '20790698077923',
   'LSADC': 'CT',
   'FUNCSTAT': 'S',
   'INTPTLAT': '+41.3270089',
   'NAME': 'Census Tract 1001',
   'OBJECTID': 6854,
   'TRACT': '100100',
   'CENTLON': '-073.2616839',
   'AREALAND': 21959638,
   'INTPTLON': '-073.2555243',
   'MTFCC': 'G5020',
   'COUNTY': '120',
   'CENT': (-73.2616839, 41.3221984),
   'INTPT': (-73.2555243, 41.3270089)}],
 '118th Congressional Districts': [{'GEOID': '0904',
   'CENTLAT': '+41.1917154',
   'CDSESSN': '118',
   'AREAWATER': 211864573,
   'STATE': '09',
   'BASENAME': '4',
   'OID': '2119031808685004',
   'LSADC': 'C2',
   'FUNCSTAT': 'N',
   'INTPTLAT': '+41.1902815',
   'NAME': 'Congressional District 4',
   'OBJECTID': 256,
   'CENTLON': '-073.3962039',
   'CD118': '04',
   'AREALAND': 1152150823,
   'INTPTLON': '-073.3933562',
   'MTFCC': 'G5200',
   'CENT': (-73.3962039, 41.1917154),
   'INTPT': (-73.3933562, 41.1902815)}]}

In [64]:
from censusgeocode import CensusGeocode
cg = CensusGeocode(benchmark='Public_AR_Current', vintage='Census2020_Current')

In [65]:
cg.coordinates(x = -95.53871, y = 30.17833)

{'2018 State Legislative Districts - Upper': [{'POP100': 1019150,
   'GEOID': '48004',
   'CENTLAT': '+29.8772005',
   'AREAWATER': 1972985466,
   'STATE': '48',
   'BASENAME': '4',
   'OID': '212704690779008',
   'LSADC': 'LU',
   'SLDU': '004',
   'FUNCSTAT': 'N',
   'INTPTLAT': '+29.8749870',
   'NAME': 'State Senate District 4',
   'OBJECTID': 771,
   'CENTLON': '-094.7002502',
   'LSY': '2018',
   'AREALAND': 6313883172,
   'INTPTLON': '-094.7127170',
   'HU100': 396829,
   'MTFCC': 'G5210',
   'LDTYP': 'O',
   'CENT': (-94.7002502, 29.8772005),
   'INTPT': (-94.712717, 29.874987)}],
 'States': [{'STATENS': '01779801',
   'POP100': 29145505,
   'GEOID': '48',
   'CENTLAT': '+31.4277553',
   'AREAWATER': 18974670781,
   'STATE': '48',
   'BASENAME': 'Texas',
   'STUSAB': 'TX',
   'OID': '2747098452115',
   'LSADC': '00',
   'FUNCSTAT': 'A',
   'INTPTLAT': '+31.4347032',
   'DIVISION': '7',
   'NAME': 'Texas',
   'REGION': '3',
   'OBJECTID': 35,
   'CENTLON': '-099.2890828',
   'AREALAND': 676685276277,
   'INTPTLON': '-099.2818238',
   'HU100': 11589324,
   'MTFCC': 'G4000',
   'UR': 'M',
   'CENT': (-99.2890828, 31.4277553),
   'INTPT': (-99.2818238, 31.4347032)}],
 'Combined Statistical Areas': [{'POP100': 7312270,
   'GEOID': '288',
   'CENTLAT': '+29.6770696',
   'AREAWATER': 4499825750,
   'BASENAME': 'Houston-The Woodlands, TX',
   'OID': '2617013782255142',
   'LSADC': 'M0',
   'FUNCSTAT': 'S',
   'INTPTLAT': '+29.6782333',
   'NAME': 'Houston-The Woodlands, TX CSA',
   'OBJECTID': 134,
   'CSA': '288',
   'CENTLON': '-095.5626786',
   'INTPTLON': '-095.5614997',
   'AREALAND': 30656587211,
   'HU100': 2821424,
   'MTFCC': 'G3100',
   'CENT': (-95.5626786, 29.6770696),
   'INTPT': (-95.5614997, 29.6782333)}],
 'County Subdivisions': [{'COUSUB': '93655',
   'POP100': 428794,
   'GEOID': '4833993655',
   'CENTLAT': '+30.2282184',
   'AREAWATER': 10076973,
   'STATE': '48',
   'BASENAME': 'Southeast Montgomery',
   'OID': '27670746284750',
   'LSADC': '22',
   'FUNCSTAT': 'S',
   'INTPTLAT': '+30.2221194',
   'NAME': 'Southeast Montgomery CCD',
   'OBJECTID': 10981,
   'CENTLON': '-095.3340921',
   'COUSUBCC': 'Z5',
   'AREALAND': 1252140544,
   'INTPTLON': '-095.3449342',
   'HU100': 162870,
   'MTFCC': 'G4040',
   'COUSUBNS': '01939213',
   'UR': 'M',
   'COUNTY': '339',
   'CENT': (-95.3340921, 30.2282184),
   'INTPT': (-95.3449342, 30.2221194)}],
 'Census Designated Places': [{'NECTAPCI': 'N',
   'POP100': 114436,
   'GEOID': '4872656',
   'CENTLAT': '+30.1738505',
   'AREAWATER': 1353716,
   'STATE': '48',
   'BASENAME': 'The Woodlands',
   'OID': '28070746285972',
   'LSADC': '57',
   'PLACE': '72656',
   'FUNCSTAT': 'S',
   'INTPTLAT': '+30.1725620',
   'NAME': 'The Woodlands CDP',
   'OBJECTID': 24336,
   'PLACECC': 'U1',
   'CENTLON': '-095.5134104',
   'CBSAPCI': 'Y',
   'AREALAND': 112245571,
   'INTPTLON': '-095.5098125',
   'HU100': 45325,
   'PLACENS': '02410076',
   'MTFCC': 'G4210',
   'UR': 'M',
   'CENT': (-95.5134104, 30.1738505),
   'INTPT': (-95.5098125, 30.172562)}],
 'Urban Areas': [{'GEOID': '87300',
   'CENTLAT': '+30.2265450',
   'OID_1': '',
   'AREAWATER': 3879014,
   'BASENAME': 'The Woodlands--Conroe, TX',
   'LSADC': '67',
   'UA': '87300',
   'FUNCSTAT': 'S',
   'INTPTLAT': '+30.2198367',
   'NAME': 'The Woodlands--Conroe, TX Urban Area',
   'OBJECTID': 2242,
   'CENTLON': '-095.4895139',
   'AREA': 768331191.064668,
   'LEN': 469099.44798039,
   'AREALAND': 567827960,
   'INTPTLON': '-095.4883684',
   'MTFCC': 'G3500',
   'CENT': (-95.4895139, 30.226545),
   'INTPT': (-95.4883684, 30.2198367)}],
 'Counties': [{'POP100': 620443,
   'GEOID': '48339',
   'CENTLAT': '+30.3001872',
   'AREAWATER': 89868467,
   'STATE': '48',
   'BASENAME': 'Montgomery',
   'OID': '27570746281935',
   'LSADC': '06',
   'FUNCSTAT': 'A',
   'INTPTLAT': '+30.2988009',
   'NAME': 'Montgomery County',
   'OBJECTID': 2115,
   'CENTLON': '-095.5028211',
   'COUNTYCC': 'H1',
   'COUNTYNS': '01383955',
   'AREALAND': 2699248493,
   'INTPTLON': '-095.5029500',
   'HU100': 238489,
   'MTFCC': 'G4020',
   'UR': 'M',
   'COUNTY': '339',
   'CENT': (-95.5028211, 30.3001872),
   'INTPT': (-95.50295, 30.2988009)}],
 '2018 State Legislative Districts - Lower': [{'POP100': 228783,
   'GEOID': '48015',
   'CENTLAT': '+30.1631487',
   'SLDL': '015',
   'AREAWATER': 4312273,
   'STATE': '48',
   'BASENAME': '15',
   'OID': '213704690782932',
   'LSADC': 'LL',
   'FUNCSTAT': 'N',
   'INTPTLAT': '+30.1636751',
   'NAME': 'State House District 15',
   'OBJECTID': 3824,
   'CENTLON': '-095.4469967',
   'LSY': '2018',
   'AREALAND': 330354849,
   'INTPTLON': '-095.4461301',
   'HU100': 88984,
   'MTFCC': 'G5220',
   'LDTYP': 'O',
   'CENT': (-95.4469967, 30.1631487),
   'INTPT': (-95.4461301, 30.1636751)}],
 '116th Congressional Districts': [{'POP100': 916386,
   'GEOID': '4808',
   'CENTLAT': '+30.8193980',
   'CDSESSN': '116',
   'AREAWATER': 410959035,
   'STATE': '48',
   'BASENAME': '8',
   'OID': '211704690225215',
   'LSADC': 'C2',
   'FUNCSTAT': 'N',
   'INTPTLAT': '+30.8332407',
   'NAME': 'Congressional District 8',
   'OBJECTID': 436,
   'CENTLON': '-095.5476753',
   'AREALAND': 15681882524,
   'INTPTLON': '-095.5436034',
   'HU100': 360050,
   'CD116': '08',
   'MTFCC': 'G5200',
   'CENT': (-95.5476753, 30.819398),
   'INTPT': (-95.5436034, 30.8332407)}],
 'Census Tracts': [{'POP100': 4469,
   'GEOID': '48339690603',
   'CENTLAT': '+30.1644887',
   'AREAWATER': 28819,
   'STATE': '48',
   'BASENAME': '6906.03',
   'OID': '2077015657192686',
   'LSADC': 'CT',
   'FUNCSTAT': 'S',
   'INTPTLAT': '+30.1714221',
   'NAME': 'Census Tract 6906.03',
   'OBJECTID': 69333,
   'TRACT': '690603',
   'CENTLON': '-095.5731194',
   'AREALAND': 14026973,
   'INTPTLON': '-095.5655424',
   'HU100': 1526,
   'MTFCC': 'G5020',
   'UR': 'M',
   'COUNTY': '339',
   'CENT': (-95.5731194, 30.1644887),
   'INTPT': (-95.5655424, 30.1714221)}],
 'Census Blocks': [{'GEOID': '483396906031000',
   'STATE': '48',
   'BASENAME': '1000',
   'LSADC': 'BK',
   'INTPTLAT': '+30.1791826',
   'OBJECTID': 6167840,
   'BLKGRP': '1',
   'AREALAND': 294704,
   'HU100': 47,
   'VINTAGE': '70',
   'LWBLKTYP': 'L',
   'UR': 'U',
   'COUNTY': '339',
   'SUFFIX': '',
   'TABBLKSUFX2': '',
   'POP100': 149,
   'CENTLAT': '+30.1791826',
   'BLOCK': '1000',
   'AREAWATER': 0,
   'OID': '210701001701494',
   'FUNCSTAT': 'S',
   'NAME': 'Block 1000',
   'TRACT': '690603',
   'CENTLON': '-095.5389121',
   'ACT': '',
   'INTPTLON': '-095.5389121',
   'MTFCC': 'G5040',
   'CENT': (-95.5389121, 30.1791826),
   'INTPT': (-95.5389121, 30.1791826)}]}